// flow-typed signature: 0e04cc4636210a031c924b62f2173b7a
// flow-typed version: <<STUB>>/exec-sh_v^0.2.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'exec-sh'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'exec-sh' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'exec-sh/example/example' {
  declare module.exports: any;
}

declare module 'exec-sh/lib/exec-sh' {
  declare module.exports: any;
}

declare module 'exec-sh/test/exec-sh' {
  declare module.exports: any;
}

// Filename aliases
declare module 'exec-sh/example/example.js' {
  declare module.exports: $Exports<'exec-sh/example/example'>;
}
declare module 'exec-sh/lib/exec-sh.js' {
  declare module.exports: $Exports<'exec-sh/lib/exec-sh'>;
}
declare module 'exec-sh/test/exec-sh.js' {
  declare module.exports: $Exports<'exec-sh/test/exec-sh'>;
}
